In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import StandardScaler



In [ ]:
# data collection
# pima diabet datassets



In [ ]:
from os import P_PID
#loading the datasets
diabetes_dataset = pd.read_csv("/content/pima-indians-diabetes.csv")

In [ ]:
pd.read_csv?

In [ ]:
#printing  first 5 rows of datasets
diabetes_dataset.head()

6  148  72  35    0  33.6  0.627  50  1
0  1   85  66  29    0  26.6  0.351  31  0
1  8  183  64   0    0  23.3  0.672  32  1
2  1   89  66  23   94  28.1  0.167  21  0
3  0  137  40  35  168  43.1  2.288  33  1
4  5  116  74   0    0  25.6  0.201  30  0

In [ ]:
# nuber of rws and columns in tis datasets
diabetes_dataset.shape

(767, 9)

In [ ]:
#getting statistical measure of the data
diabetes_dataset.describe()

6         148          72          35           0        33.6  \
count  767.000000  767.000000  767.000000  767.000000  767.000000  767.000000   
mean     3.842243  120.859192   69.101695   20.517601   79.903520   31.990482   
std      3.370877   31.978468   19.368155   15.954059  115.283105    7.889091   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   
50%      3.000000  117.000000   72.000000   23.000000   32.000000   32.000000   
75%      6.000000  140.000000   80.000000   32.000000  127.500000   36.600000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000   

            0.627          50           1  
count  767.000000  767.000000  767.000000  
mean     0.471674   33.219035    0.348110  
std      0.331497   11.752296    0.476682  
min      0.078000   21.000000    0.000000  
25%      0.243500   24.000000    0.000000  
50%      0.371000   29.000000    0.000000  
75%      0.625000   41.000000    1.000000  
max      2.420000   81.000000    1.000000

In [ ]:
diabetes_dataset.columns=["Pregnancies","Glucose","BloodPressure","SkinThickness","Insulin","BMI","DiabetsPedigreeFuction","Age","Outcome"]
diabetes_dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            1       85             66             29        0  26.6   
1            8      183             64              0        0  23.3   
2            1       89             66             23       94  28.1   
3            0      137             40             35      168  43.1   
4            5      116             74              0        0  25.6   

   DiabetsPedigreeFuction  Age  Outcome  
0                   0.351   31        0  
1                   0.672   32        1  
2                   0.167   21        0  
3                   2.288   33        1  
4                   0.201   30        0

In [ ]:
diabetes_dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   767.000000  767.000000     767.000000     767.000000  767.000000   
mean      3.842243  120.859192      69.101695      20.517601   79.903520   
std       3.370877   31.978468      19.368155      15.954059  115.283105   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   32.000000   
75%       6.000000  140.000000      80.000000      32.000000  127.500000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetsPedigreeFuction         Age     Outcome  
count  767.000000              767.000000  767.000000  767.000000  
mean    31.990482                0.471674   33.219035    0.348110  
std      7.889091                0.331497   11.752296    0.476682  
min      0.000000                0.078000   21.000000    0.000000  
25%     27.300000                0.243500   24.000000    0.000000  
50%     32.000000                0.371000   29.000000    0.000000  
75%     36.600000                0.625000   41.000000    1.000000  
max     67.100000                2.420000   81.000000    1.000000

In [ ]:
diabetes_dataset['Outcome'].value_counts()

0    500
1    267
Name: Outcome, dtype: int64

In [ ]:
# 0 is for non diabetic
# 1 is for diabetic

In [ ]:
diabetes_dataset.groupby('Outcome').mean()

Pregnancies    Glucose  BloodPressure  SkinThickness    Insulin  \
Outcome                                                                    
0           3.298000  109.98000      68.184000      19.664000   68.79200   
1           4.861423  141.23221      70.820225      22.116105  100.71161   

               BMI  DiabetsPedigreeFuction        Age  
Outcome                                                
0        30.304200                0.429734  31.190000  
1        35.148315                0.550213  37.018727

In [ ]:
#separete data
x = diabetes_dataset.drop(columns ='Outcome', axis=1).to_numpy()
y = diabetes_dataset['Outcome'].to_numpy()
x

array([[1.00e+00, 8.50e+01, 6.60e+01, ..., 2.66e+01, 3.51e-01, 3.10e+01],
       [8.00e+00, 1.83e+02, 6.40e+01, ..., 2.33e+01, 6.72e-01, 3.20e+01],
       [1.00e+00, 8.90e+01, 6.60e+01, ..., 2.81e+01, 1.67e-01, 2.10e+01],
       ...,
       [5.00e+00, 1.21e+02, 7.20e+01, ..., 2.62e+01, 2.45e-01, 3.00e+01],
       [1.00e+00, 1.26e+02, 6.00e+01, ..., 3.01e+01, 3.49e-01, 4.70e+01],
       [1.00e+00, 9.30e+01, 7.00e+01, ..., 3.04e+01, 3.15e-01, 2.30e+01]])

In [ ]:
print(x)

[[1.00e+00 8.50e+01 6.60e+01 ... 2.66e+01 3.51e-01 3.10e+01]
 [8.00e+00 1.83e+02 6.40e+01 ... 2.33e+01 6.72e-01 3.20e+01]
 [1.00e+00 8.90e+01 6.60e+01 ... 2.81e+01 1.67e-01 2.10e+01]
 ...
 [5.00e+00 1.21e+02 7.20e+01 ... 2.62e+01 2.45e-01 3.00e+01]
 [1.00e+00 1.26e+02 6.00e+01 ... 3.01e+01 3.49e-01 4.70e+01]
 [1.00e+00 9.30e+01 7.00e+01 ... 3.04e+01 3.15e-01 2.30e+01]]


In [ ]:
y

array([0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,

In [ ]:
# data standdisation
scaler = StandardScaler()

In [ ]:
scaler.fit(x)

StandardScaler()

In [ ]:
standardize_data = scaler.transform(x)

In [ ]:
print(standardize_data)

[[-0.84372629 -1.12208597 -0.16024856 ... -0.68372895 -0.36426474
  -0.18894038]
 [ 1.23423997  1.94447577 -0.26357823 ... -1.10230105  0.60470064
  -0.1037951 ]
 [-0.84372629 -0.99692019 -0.16024856 ... -0.49346891 -0.91968415
  -1.0403932 ]
 ...
 [ 0.343683    0.0044061   0.14974046 ... -0.73446496 -0.68423462
  -0.27408566]
 [-0.84372629  0.16086333 -0.47023757 ... -0.23978884 -0.37030191
   1.17338414]
 [-0.84372629 -0.8717544   0.04641078 ... -0.20173684 -0.47293375
  -0.87010264]]


In [ ]:
x = standardize_data
print(x)
print(y)

[[-0.84372629 -1.12208597 -0.16024856 ... -0.68372895 -0.36426474
  -0.18894038]
 [ 1.23423997  1.94447577 -0.26357823 ... -1.10230105  0.60470064
  -0.1037951 ]
 [-0.84372629 -0.99692019 -0.16024856 ... -0.49346891 -0.91968415
  -1.0403932 ]
 ...
 [ 0.343683    0.0044061   0.14974046 ... -0.73446496 -0.68423462
  -0.27408566]
 [-0.84372629  0.16086333 -0.47023757 ... -0.23978884 -0.37030191
   1.17338414]
 [-0.84372629 -0.8717544   0.04641078 ... -0.20173684 -0.47293375
  -0.87010264]]
[0 1 0 1 0 1 0 1 1 0 1 0 1 1 1 1 1 0 1 0 0 1 1 1 1 1 0 0 0 0 1 0 0 0 0 0 1
 1 1 0 0 0 1 0 1 0 0 1 0 0 0 0 1 0 0 1 0 0 0 0 1 0 0 1 0 1 0 0 0 1 0 1 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1
 0 0 1 1 1 0 0 0 1 0 0 0 1 1 0 0 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 1 1 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 1 0 0 0 1 0 1 0 1 0 0 0 0 0 1
 1 1 1 1 0 0 1 1 0 1 0 1 1 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 1 1 1 1 0
 0 0 0 0 1 0 0 1 1 0 0 0 1 1 1 1 0 0 0 1 1 0 1 0 0 0 0 0 0

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.20, stratify= y, random_state = 0)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(767, 8) (613, 8) (154, 8)


In [ ]:
#trainning the model

classifier = svm.SVC(kernel="linear")


In [ ]:
# training the support vector

classifier.fit(x_train,y_train)


SVC(kernel='linear')

In [ ]:
# model evaluation
# accuraccy score on trainning

x_trai_prediction = classifier.predict(x_test)
trainning_data_accuracy = accuracy_score(x_trai_prediction,y_train)

ValueError: ignored

In [ ]:
print("accuracy of trainning data :", trainning_data_accuracy)

accuracy of trainning data : 0.7797716150081566


In [ ]:
# accuraccy score on testing

x_test_prediction = classifier.predict(x_test)
testing_data_accuracy = accuracy_score(x_test_prediction,y_test)

In [ ]:
print("accuracy of testing data :", testing_data_accuracy)

accuracy of testing data : 0.7662337662337663


In [ ]:
x

array([[-1.14057861,  0.53636068, -0.47023757, ...,  0.33099129,
         0.18813609, -1.0403932 ],
       [ 0.93738765,  0.66152647, -0.47023757, ..., -0.40468088,
         0.6499794 ,  2.3654181 ],
       [ 1.5310923 ,  0.28602911,  0.04641078, ...,  0.28025528,
         0.54432897,  1.00309358],
       ...,
       [-0.54687397, -0.02688535, -0.78022659, ..., -0.65836094,
        -0.05033203, -0.52952151],
       [ 1.23423997, -0.02688535,  0.87304816, ..., -0.4554169 ,
        -0.64197444, -0.95524792],
       [-0.84372629,  0.72410936,  0.66638881, ...,  1.78965164,
        -0.41256208,  1.08823886]])

In [ ]:

# making a predictive system
input_data = (1,89,66,23,94,28.1,0.167,21)
# change input data into numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape thhe arraay
input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

# standardise the input data
std_data = scaler.transform(input_data_reshape)
print(std_data)
prediction = classifier.predict(std_data)
print(prediction)



if (prediction == 0):
  print("person is not a diabetic")
else:
  print("person is a diabetic") 

  

[[-0.84372629 -0.99692019 -0.16024856  0.15569823  0.12235685 -0.49346891
  -0.91968415 -1.0403932 ]]
[0]
person is not a diabetic


In [ ]:
 # saving thhe model

In [ ]:
import pickle
filename = 'trained_model.sav'
pickle.dump(classifier, open(filename,'wb'))


In [ ]:
#loading the saved model
loaded_model = pickle.load(open('trained_model.sav','rb'))

In [ ]:

# making a predictive system
input_data = (1,89,66,23,94,28.1,0.167,21)
# change input data into numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape thhe arraay
input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

# standardise the input data
std_data = scaler.transform(input_data_reshape)
print(std_data)
prediction = loaded_model.predict(std_data)
print(prediction)



if (prediction == 0):
  print("person is not a diabetic")
else:
  print("person is a diabetic") 

[[-0.84372629 -0.99692019 -0.16024856  0.15569823  0.12235685 -0.49346891
  -0.91968415 -1.0403932 ]]
[0]
person is not a diabetic
